src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
class Client
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birth_date;

    /**
     * @ORM\OneToMany(targetEntity=Schedule::class, mappedBy="client")
     */
    private $Schedule;

  

    public function __construct()
    {
        $this->schedule = new ArrayCollection();
        $this->Schedule = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(?\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    /**
     * @return Collection|Schedule[]
     */
    public function getSchedule(): Collection
    {
        return $this->schedule;
    }

    public function addSchedule(Schedule $schedule): self
    {
        if (!$this->schedule->contains($schedule)) {
            $this->schedule[] = $schedule;
            $schedule->setClient($this);
        }

        return $this;
    }

    public function removeSchedule(Schedule $schedule): self
    {
        if ($this->schedule->removeElement($schedule)) {
            // set the owning side to null (unless already changed)
            if ($schedule->getClient() === $this) {
                $schedule->setClient(null);
            }
        }

        return $this;
    }
    public function __toString() {
        return ($this->first_name.' '.$this->last_name);
    }
}

src/Entity/Doctor.php
<?php

namespace App\Entity;

use App\Repository\DoctorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DoctorRepository::class)
 */
class Doctor
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=8, nullable=true)
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $startTime;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $endTime;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $session_duration;

    /**
     * @ORM\OneToMany(targetEntity=Schedule::class, mappedBy="doctor")
     */
    private $schedule;

    public function __construct()
    {
        $this->schedule = new ArrayCollection();
    }

 

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(?string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getStartTime(): ?string
    {
        return $this->startTime;
    }

    public function setStartTime(string $startTime): self
    {
        $this->startTime = $startTime;

        return $this;
    }

    public function getEndTime(): ?string
    {
        return $this->endTime;
    }

    public function setEndTime(string $endTime): self
    {
        $this->endTime = $endTime;

        return $this;
    }

    public function getSessionDuration(): ?string
    {
        return $this->session_duration;
    }

    public function setSessionDuration(string $session_duration): self
    {
        $this->session_duration = $session_duration;

        return $this;
    }

    public function getSchedule(): ?Schedule
    {
        return $this->schedule;
    }

    public function setSchedule(?Schedule $schedule): self
    {
        $this->schedule = $schedule;

        return $this;
    }
    public function __toString() {
        return ($this->first_name.' '.$this->last_name);
    }

    public function addSchedule(Schedule $schedule): self
    {
        if (!$this->schedule->contains($schedule)) {
            $this->schedule[] = $schedule;
            $schedule->setDoctor($this);
        }

        return $this;
    }

    public function removeSchedule(Schedule $schedule): self
    {
        if ($this->schedule->removeElement($schedule)) {
            // set the owning side to null (unless already changed)
            if ($schedule->getDoctor() === $this) {
                $schedule->setDoctor(null);
            }
        }

        return $this;
    }
}

src/Entity/Schedule.php
<?php

namespace App\Entity;

use App\Repository\ScheduleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ScheduleRepository::class)
 */
class Schedule
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $appointment;

    /**
     * @ORM\ManyToOne(targetEntity=Doctor::class, inversedBy="schedule")
     */
    private $doctor;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="Schedule")
     */
    private $client;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAppointment(): ?\DateTimeInterface
    {
        return $this->appointment;
    }

    public function setAppointment(\DateTimeInterface $appointment): self
    {
        $this->appointment = $appointment;

        return $this;
    }

    

    public function addDoctor(Doctor $doctor): self
    {
        if (!$this->doctor->contains($doctor)) {
            $this->doctor[] = $doctor;
            $doctor->setSchedule($this);
        }

        return $this;
    }

    public function removeDoctor(Doctor $doctor): self
    {
        if ($this->doctor->removeElement($doctor)) {
            // set the owning side to null (unless already changed)
            if ($doctor->getSchedule() === $this) {
                $doctor->setSchedule(null);
            }
        }

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }
    
    public function getDoctor(): ?doctor
    {
        return $this->doctor;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function __toString() {
        return $this->id;
    }

    public function setDoctor(?Doctor $doctor): self
    {
        $this->doctor = $doctor;

        return $this;
    }
}

src/Form/ScheduleType.php
<?php

namespace App\Form;

use App\Entity\Schedule;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType ;

class ScheduleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
       
        $builder
            ->add('appointment', DateTimeType::class,[
                'date_widget' => 'single_text',
                'hours' => range(8,18)
                
            ])
            ->add('doctor')
            ->add('client')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Schedule::class,
        ]);
    }
}

src/Controller/ScheduleController.php
<?php

namespace App\Controller;

use App\Entity\Schedule;
use App\Form\ScheduleType;
use App\Repository\ScheduleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/schedule")
 */
class ScheduleController extends AbstractController
{
    /**
     * @Route("/", name="schedule_index", methods={"GET"})
     */
    public function index(ScheduleRepository $scheduleRepository): Response
    {

        $events = $scheduleRepository->findAll();
       // dd($events);
        $rdvs =[];

        foreach ($events as $event) {
            $rdvs[] = [
                'id'=> $event->getID(),
                'appointment'=> $event->getappointment()->format('Y-M-D H:i:s'),
                'start' => $event->getappointment()->format('Y-M-D H:i:s'),
                'end'=> $event->getappointment()->format('Y-M-D H:i:s')
            ];
        }

        $data= json_encode($rdvs);


        return $this->render('schedule/index.html.twig', [
            'schedules' => $scheduleRepository->findAll(),
        ]);
    }

    public function getData(ScheduleRepository $scheduleRepository): String
    {
        $events = $scheduleRepository->findAll();
        //dd($event);
        $rdvs =[];

        foreach ($events as $event) {
            $rdvs[] = [
                'id'=> $event->getID(),
                'appointment'=> $event->getappointment(),
                'start' => $event->getappointment()->format('Y-M-D H:i:s'),
                'end'=> $event->getappointment()->format('Y-M-D H:i:s')
            ];
        }

        $data= json_encode($rdvs);


        return ($data);
    }



    /**
     * @Route("/new", name="schedule_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $schedule = new Schedule();
        $form = $this->createForm(ScheduleType::class, $schedule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($schedule);
            $entityManager->flush();

            return $this->redirectToRoute('schedule_index');
        }

        return $this->render('schedule/new.html.twig', [
            'schedule' => $schedule,
            'form' => $form->createView(),
        ]);
    }


  
    /**
     * @Route("/{id}", name="schedule_show", methods={"GET"})
     */
    public function show(Schedule $schedule): Response
    {
        return $this->render('schedule/show2.html.twig', [
            'schedule' => $schedule,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="schedule_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Schedule $schedule): Response
    {
        $form = $this->createForm(ScheduleType::class, $schedule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('schedule_index');
        }

        return $this->render('schedule/edit.html.twig', [
            'schedule' => $schedule,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="schedule_delete", methods={"POST"})
     */
    public function delete(Request $request, Schedule $schedule): Response
    {
        if ($this->isCsrfTokenValid('delete'.$schedule->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($schedule);
            $entityManager->flush();
        }

        return $this->redirectToRoute('schedule_index');
    }
}

templates/schedule/_delete_form.html.twig
<form method="post" action="{{ path('schedule_delete', {'id': schedule.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ schedule.id) }}">
	<button class="btn">Supprimer</button>
</form>

templates/schedule/_form.html.twig
{{ form_start(form) }}
{{ form_label(form.appointment, 'Sélectionner Rendez-vous : ') }}
{{ form_widget(form.appointment, {'attr': {'class': 'form-control','style': 'width:40%;'}}) }}
{{ form_label(form.doctor, 'Sélectionner le médecin : ') }}
{{ form_widget(form.doctor, {'attr': {'class': 'form-control','style': 'width:40%;'}}) }}
{{ form_label(form.client, 'Sélectionner le patient : ') }}
{{ form_widget(form.client, {'attr': {'class': 'form-control','style': 'width:40%;'}}) }}
<button class="btn btn-success pull-right">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/schedule/edit.html.twig
<!DOCTYPE html>

<title>Edit Schedule</title>

{% block body %}
    <h1>Edit Schedule</h1>
    {{ form_row(form.doctor, { 'attr':{'disabled':'disabled'} }) }}
    {{ form_row(form.client, { 'attr':{'disabled':'disabled'} }) }}
    {{ include('schedule/_form.html.twig', {'button_label': 'Update'}) }}
    {{ include('schedule/_delete_form.html.twig') }}
    <a href="{{ path('schedule_index') }}">back to list</a>
{% endblock %}

templates/schedule/index.html.twig
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>Bootstrap CRUD Data Table for Database with Modal Form</title>
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
		<style>
			body {
				color: #566787;
				background: #f5f5f5;
				font-family: 'Varela Round', sans-serif;
				font-size: 13px;
			}
			.table-responsive {
				margin: 30px 0;
			}
			.table-wrapper {
				background: #fff;
				padding: 20px 25px;
				border-radius: 3px;
				min-width: 1000px;
				box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
			}
			.table-title {
				padding: 16px 30px;
				color: #fff;
				min-width: 100%;
				margin: -20px -25px 10px;
			}
			.table-title h2 {
				margin: 5px 0 0;
				font-size: 24px;
			}
			.table-title .btn-group {
				float: right;
			}
			.table-title .btn {
				color: #fff;
				float: right;
				font-size: 13px;
				border: none;
				min-width: 50px;
				border-radius: 2px;
				border: none;
				outline: none !important;
				margin-left: 10px;
			}
			.table-title .btn i {
				float: left;
				font-size: 21px;
				margin-right: 5px;
			}
			.table-title .btn span {
				float: left;
				margin-top: 2px;
			}
			table.table tr th,
			table.table tr td {
				border-color: #e9e9e9;
				padding: 12px 15px;
				vertical-align: middle;
			}
			table.table-striped tbody tr:nth-of-type(odd) {
				background-color: #fcfcfc;
			}
			table.table-striped.table-hover tbody tr:hover {
				background: #f5f5f5;
			}
			table.table th i {
				font-size: 13px;
				margin: 0 5px;
				cursor: pointer;
			}
			table.table td:last-child i {
				opacity: 0.9;
				font-size: 22px;
				margin: 0 5px;
			}
			table.table td a {
				font-weight: bold;
				color: #566787;
				display: inline-block;
				text-decoration: none;
				outline: none !important;
			}
			table.table td a:hover {
				color: #2196F3;
			}
			table.table td a.edit {
				color: #FFC107;
			}
			table.table td a.delete {
				color: #F44336;
			}
			table.table td i {
				font-size: 19px;
			}
			table.table .avatar {
				border-radius: 50%;
				vertical-align: middle;
				margin-right: 10px;
			}
			.pagination {
				float: right;
				margin: 0 0 5px;
			}
			.pagination li a {
				border: none;
				font-size: 13px;
				min-width: 30px;
				min-height: 30px;
				color: #999;
				margin: 0 2px;
				line-height: 30px;
				border-radius: 2px !important;
				text-align: center;
				padding: 0 6px;
			}
			.pagination li a:hover {
				color: #666;
			}
			.pagination li.active a,
			.pagination li.active a.page-link {
				background: #03A9F4;
			}
			.pagination li.active a:hover {
				background: #0397d6;
			}
			.pagination li.disabled i {
				color: #ccc;
			}
			.pagination li i {
				font-size: 16px;
				padding-top: 6px
			}
			.hint-text {
				float: left;
				margin-top: 10px;
				font-size: 13px;
			}
			/* Modal styles */
			.modal .modal-dialog {
				max-width: 400px;
			}
			.modal .modal-header,
			.modal .modal-body,
			.modal .modal-footer {
				padding: 20px 30px;
			}
			.modal .modal-content {
				border-radius: 3px;
				font-size: 14px;
			}
			.modal .modal-footer {
				background: #ecf0f1;
				border-radius: 0 0 3px 3px;
			}
			.modal .modal-title {
				display: inline-block;
			}
			.modal .form-control {
				border-radius: 2px;
				box-shadow: none;
				border-color: #dddddd;
			}
			.modal textarea.form-control {
				resize: vertical;
			}
			.modal .btn {
				border-radius: 2px;
				min-width: 100px;
			}
			.modal form label {
				font-weight: normal;
			}
		</style>
		<script>
			$(document).ready(function () { // Activate tooltip
$('[data-toggle="tooltip"]').tooltip();

// Select/Deselect checkboxes
var checkbox = $('table tbody input[type="checkbox"]');
$("#selectAll").click(function () {
if (this.checked) {
checkbox.each(function () {
this.checked = true;
});
} else {
checkbox.each(function () {
this.checked = false;
});
}
});
checkbox.click(function () {
if (!this.checked) {
$("#selectAll").prop("checked", false);
}
});
});
		</script>
	</head>
	<body>
		<div class="container-xl">
			<div class="table-responsive">
				<div class="table-wrapper">
					<div class="table-title">
						<div class="row">
							<div class="col-sm-12">
								<a href="{{ path('schedule_new') }}" class="btn btn-success">
									<i class="material-icons">&#xE147;</i>
									<span>Prendre un rendez-vous</span>
								</a>
							</div>
						</div>
					</div>
					{% block body %}
						<h1 style="text-align: center">Liste des rendez-vous</h1>

						<table class="table table-striped table-hover">
							<thead>
								<tr>

									<th>Date</th>
									<th>Médecin</th>
									<th>Patient</th>
									<th>Actions</th>
								</tr>
							</thead>
							<tbody>
								{% for schedule in schedules %}
									<tr>
										<td>{{ schedule.appointment ? schedule.appointment|date('Y-m-d H:i:s') : '' }}</td>
										<td>{{schedule.doctor.firstName}}<span></span>
											{{schedule.doctor.lastName}}</td>
										<td>{{schedule.client.firstName}}<span></span>
											{{schedule.client.lastName}}</td>
										<td>
											<a href="{{ path('schedule_show', {'id': schedule.id}) }}">Afficher</a>
											<a href="{{ path('schedule_edit', {'id': schedule.id}) }}">Modifier</a>
										</td>
									</tr>
								{% else %}
									<tr>
										<td colspan="3">Aucun rendez-vous n'est trouvé</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>

					{% endblock %}
				</div>
			</div>
		</div>
	</body>
</html>

templates/schedule/show.html.twig
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>Bootstrap CRUD Data Table for Database with Modal Form</title>
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
		<style>
			body {
				color: #566787;
				background: #f5f5f5;
				font-family: 'Varela Round', sans-serif;
				font-size: 13px;
			}
			.table-responsive {
				margin: 30px 0;
			}
			.table-wrapper {
				background: #fff;
				padding: 20px 25px;
				border-radius: 3px;
				min-width: 1000px;
				box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
			}
			.table-title {
				padding: 16px 30px;
				color: #fff;
				min-width: 100%;
				margin: -20px -25px 10px;
			}
			.table-title h2 {
				margin: 5px 0 0;
				font-size: 24px;
			}
			.table-title .btn-group {
				float: right;
			}
			.table-title .btn {
				color: #fff;
				float: right;
				font-size: 13px;
				border: none;
				min-width: 50px;
				border-radius: 2px;
				border: none;
				outline: none !important;
				margin-left: 10px;
			}
			.table-title .btn i {
				float: left;
				font-size: 21px;
				margin-right: 5px;
			}
			.table-title .btn span {
				float: left;
				margin-top: 2px;
			}
			table.table tr th,
			table.table tr td {
				border-color: #e9e9e9;
				padding: 12px 15px;
				vertical-align: middle;
			}
			table.table-striped tbody tr:nth-of-type(odd) {
				background-color: #fcfcfc;
			}
			table.table-striped.table-hover tbody tr:hover {
				background: #f5f5f5;
			}
			table.table th i {
				font-size: 13px;
				margin: 0 5px;
				cursor: pointer;
			}
			table.table td:last-child i {
				opacity: 0.9;
				font-size: 22px;
				margin: 0 5px;
			}
			table.table td a {
				font-weight: bold;
				color: #566787;
				display: inline-block;
				text-decoration: none;
				outline: none !important;
			}
			table.table td a:hover {
				color: #2196F3;
			}
			table.table td a.edit {
				color: #FFC107;
			}
			table.table td a.delete {
				color: #F44336;
			}
			table.table td i {
				font-size: 19px;
			}
			table.table .avatar {
				border-radius: 50%;
				vertical-align: middle;
				margin-right: 10px;
			}
			.pagination {
				float: right;
				margin: 0 0 5px;
			}
			.pagination li a {
				border: none;
				font-size: 13px;
				min-width: 30px;
				min-height: 30px;
				color: #999;
				margin: 0 2px;
				line-height: 30px;
				border-radius: 2px !important;
				text-align: center;
				padding: 0 6px;
			}
			.pagination li a:hover {
				color: #666;
			}
			.pagination li.active a,
			.pagination li.active a.page-link {
				background: #03A9F4;
			}
			.pagination li.active a:hover {
				background: #0397d6;
			}
			.pagination li.disabled i {
				color: #ccc;
			}
			.pagination li i {
				font-size: 16px;
				padding-top: 6px
			}
			.hint-text {
				float: left;
				margin-top: 10px;
				font-size: 13px;
			}
			/* Modal styles */
			.modal .modal-dialog {
				max-width: 400px;
			}
			.modal .modal-header,
			.modal .modal-body,
			.modal .modal-footer {
				padding: 20px 30px;
			}
			.modal .modal-content {
				border-radius: 3px;
				font-size: 14px;
			}
			.modal .modal-footer {
				background: #ecf0f1;
				border-radius: 0 0 3px 3px;
			}
			.modal .modal-title {
				display: inline-block;
			}
			.modal .form-control {
				border-radius: 2px;
				box-shadow: none;
				border-color: #dddddd;
			}
			.modal textarea.form-control {
				resize: vertical;
			}
			.modal .btn {
				border-radius: 2px;
				min-width: 100px;
			}
			.modal form label {
				font-weight: normal;
			}
		</style>
		<script>
			$(document).ready(function () { // Activate tooltip
$('[data-toggle="tooltip"]').tooltip();

// Select/Deselect checkboxes
var checkbox = $('table tbody input[type="checkbox"]');
$("#selectAll").click(function () {
if (this.checked) {
checkbox.each(function () {
this.checked = true;
});
} else {
checkbox.each(function () {
this.checked = false;
});
}
});
checkbox.click(function () {
if (!this.checked) {
$("#selectAll").prop("checked", false);
}
});
});
		</script>
	</head>
	<body>
		<div class="container-xl">
			<div class="table-responsive">
				<div class="table-wrapper">
					<div class="table-title">
						<div class="row">
							<div class="col-sm-12">
								<a href="{{ path('schedule_new') }}" class="btn btn-success">
									<i class="material-icons">&#xE147;</i>
									<span>Prendre un rendez-vous</span>
								</a>
							</div>
						</div>
					</div>
					{% block body %}
						{% block javascript %}
							<script>

								window.onload = () => {
let calendarEl = document.getElementById('calendar');
let calendar = new FullCalendar.Calendar(calendarEl, {
initialView: 'timeGridWeek',
locale: 'fr',
slotMinTime: "{{ doctor.startTime }}",
slotMaxTime: "{{ doctor.endTime }}",
slotDuration:"{{ doctor.sessionDuration }}",
height: "auto"
});
calendar.render();
};
							</script>
						{% endblock %}

						<div class="row">
							<div class="col-md-">
								<a href="{{ path('schedule_index') }}" class="btn btn-success">
									<i class="material-icons">&#xe5c4;</i>
									<span>Liste des rendez-vous</span>
								</a>

							</div>

							<div class="col-md-3"></div>
							<div class="col-md-3">
								<a href="{{ path('schedule_edit', {'id': schedule.id}) }}" class="btn btn-warning">
									<i class="material-icons">&#xe3c9;</i>
									<span>Modifier ce rendez-vous</span>
								</a>
							</div>
							<div class="col-md-3">
								<a href="{{ path('schedule_delete', {'id': schedule.id}) }}" class="btn btn-danger">
									<i class="material-icons">&#xe872;</i>
									<span>Supprimer ce rendez-vous</span>
								</a>
							</div>
						</div>
					{% endblock %}
				</div>
			</div>
		</body>
	</body>
</html></div></body></html>