src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
class Client
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birth_date;

    /**
     * @ORM\OneToMany(targetEntity=Schedule::class, mappedBy="client")
     */
    private $Schedule;

  

    public function __construct()
    {
        $this->schedule = new ArrayCollection();
        $this->Schedule = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(?\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    /**
     * @return Collection|Schedule[]
     */
    public function getSchedule(): Collection
    {
        return $this->schedule;
    }

    public function addSchedule(Schedule $schedule): self
    {
        if (!$this->schedule->contains($schedule)) {
            $this->schedule[] = $schedule;
            $schedule->setClient($this);
        }

        return $this;
    }

    public function removeSchedule(Schedule $schedule): self
    {
        if ($this->schedule->removeElement($schedule)) {
            // set the owning side to null (unless already changed)
            if ($schedule->getClient() === $this) {
                $schedule->setClient(null);
            }
        }

        return $this;
    }
    public function __toString() {
        return ($this->first_name.' '.$this->last_name);
    }
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('first_name')
            ->add('last_name')
            ->add('birth_date', DateType::class, [
                'widget' => 'single_text',
                // this is actually the default format for single_text
                'format' => 'yyyy-MM-dd',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/client")
 */
class ClientController extends AbstractController
{
    /**
     * @Route("/", name="client_index", methods={"GET"})
     */
    public function index(ClientRepository $clientRepository): Response
    {
        return $this->render('client/index.html.twig', [
            'clients' => $clientRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="client_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $client = new Client();
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($client);
            $entityManager->flush();

            return $this->redirectToRoute('client_index');
        }

        return $this->render('client/new.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="client_show", methods={"GET"})
     */
    public function show(Client $client): Response
    {
        return $this->render('client/show.html.twig', [
            'client' => $client,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="client_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Client $client): Response
    {
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('client_index');
        }

        return $this->render('client/edit.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="client_delete", methods={"POST"})
     */
    public function delete(Request $request, Client $client): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($client);
            $entityManager->flush();
        }

        return $this->redirectToRoute('client_index');
    }
}

templates/client/_delete_form.html.twig
<form method="post" action="{{ path('client_delete', {'id': client.id}) }}" onsubmit="return confirm('Êtes-vous sûr de bien vouloir supprimer cet patient?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
	<button class="btn">Supprimer</button>
</form>

templates/client/_form.html.twig
{{ form_start(form) }}
{{ form_label(form.first_name, 'Prénom : ') }}
{{ form_widget(form.first_name, {'attr': {'class': 'form-control','style': 'width:40%;'}}) }}
{{ form_label(form.last_name, 'Nom : ') }}
{{ form_widget(form.last_name, {'attr': {'class': 'form-control','style': 'width:40%;'}}) }}
{{ form_label(form.birth_date, 'Date de naissance : ') }}
{{ form_widget(form.birth_date, {'attr': {'class': 'form-control','style': 'width:40%;'}}) }}
<button class="btn btn-success pull-right">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/client/edit.html.twig
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
		<style>
			body {
				color: #566787;
				background: #f5f5f5;
				font-family: 'Varela Round', sans-serif;
				font-size: 13px;
			}
			.table-responsive {
				margin: 30px 0;
			}
			.table-wrapper {
				background: #fff;
				padding: 20px 25px;
				border-radius: 3px;
				min-width: 1000px;
				box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
			}
			.table-title {
				padding: 16px 30px;
				background: #435d7d;
				color: #fff;
				min-width: 100%;
				margin: -20px -25px 10px;
			}
			.table-title h2 {
				margin: 5px 0 0;
				font-size: 24px;
			}
			.table-title .btn-group {
				float: right;
			}
			.table-title .btn {
				color: #fff;
				float: right;
				font-size: 13px;
				border: none;
				min-width: 50px;
				border-radius: 2px;
				border: none;
				outline: none !important;
				margin-left: 10px;
			}
			.table-title .btn i {
				float: left;
				font-size: 21px;
				margin-right: 5px;
			}
			.table-title .btn span {
				float: left;
				margin-top: 2px;
			}
			table.table tr th,
			table.table tr td {
				border-color: #e9e9e9;
				padding: 12px 15px;
				vertical-align: middle;
			}
			table.table tr th:first-child {
				width: 60px;
			}
			table.table tr th:last-child {
				width: 100px;
			}
			table.table-striped tbody tr:nth-of-type(odd) {
				background-color: #fcfcfc;
			}
			table.table-striped.table-hover tbody tr:hover {
				background: #f5f5f5;
			}
			table.table th i {
				font-size: 13px;
				margin: 0 5px;
				cursor: pointer;
			}
			table.table td:last-child i {
				opacity: 0.9;
				font-size: 22px;
				margin: 0 5px;
			}
			table.table td a {
				font-weight: bold;
				color: #566787;
				display: inline-block;
				text-decoration: none;
				outline: none !important;
			}
			table.table td a:hover {
				color: #2196F3;
			}
			table.table td a.edit {
				color: #FFC107;
			}
			table.table td a.delete {
				color: #F44336;
			}
			table.table td i {
				font-size: 19px;
			}
			table.table .avatar {
				border-radius: 50%;
				vertical-align: middle;
				margin-right: 10px;
			}
			.pagination {
				float: right;
				margin: 0 0 5px;
			}
			.pagination li a {
				border: none;
				font-size: 13px;
				min-width: 30px;
				min-height: 30px;
				color: #999;
				margin: 0 2px;
				line-height: 30px;
				border-radius: 2px !important;
				text-align: center;
				padding: 0 6px;
			}
			.pagination li a:hover {
				color: #666;
			}
			.pagination li.active a,
			.pagination li.active a.page-link {
				background: #03A9F4;
			}
			.pagination li.active a:hover {
				background: #0397d6;
			}
			.pagination li.disabled i {
				color: #ccc;
			}
			.pagination li i {
				font-size: 16px;
				padding-top: 6px
			}
			.hint-text {
				float: left;
				margin-top: 10px;
				font-size: 13px;
			}
			/* Custom checkbox */
			.custom-checkbox {
				position: relative;
			}
			.custom-checkbox input[type="checkbox"] {
				opacity: 0;
				position: absolute;
				margin: 5px 0 0 3px;
				z-index: 9;
			}
			.custom-checkbox label:before {
				width: 18px;
				height: 18px;
			}
			.custom-checkbox label:before {
				content: '';
				margin-right: 10px;
				display: inline-block;
				vertical-align: text-top;
				background: white;
				border: 1px solid #bbb;
				border-radius: 2px;
				box-sizing: border-box;
				z-index: 2;
			}
			.custom-checkbox input[type="checkbox"]:checked + label:after {
				content: '';
				position: absolute;
				left: 6px;
				top: 3px;
				width: 6px;
				height: 11px;
				border: solid #000;
				border-width: 0 3px 3px 0;
				transform: inherit;
				z-index: 3;
				transform: rotateZ(45deg);
			}
			.custom-checkbox input[type="checkbox"]:checked + label:before {
				border-color: #03A9F4;
				background: #03A9F4;
			}
			.custom-checkbox input[type="checkbox"]:checked + label:after {
				border-color: #fff;
			}
			.custom-checkbox input[type="checkbox"]:disabled + label:before {
				color: #b8b8b8;
				cursor: auto;
				box-shadow: none;
				background: #ddd;
			}
			/* Modal styles */
			.modal .modal-dialog {
				max-width: 400px;
			}
			.modal .modal-header,
			.modal .modal-body,
			.modal .modal-footer {
				padding: 20px 30px;
			}
			.modal .modal-content {
				border-radius: 3px;
				font-size: 14px;
			}
			.modal .modal-footer {
				background: #ecf0f1;
				border-radius: 0 0 3px 3px;
			}
			.modal .modal-title {
				display: inline-block;
			}
			.modal .form-control {
				border-radius: 2px;
				box-shadow: none;
				border-color: #dddddd;
			}
			.modal textarea.form-control {
				resize: vertical;
			}
			.modal .btn {
				border-radius: 2px;
				min-width: 100px;
			}
			.modal form label {
				font-weight: normal;
			}
		</style>
		<script>
			$(document).ready(function () { // Activate tooltip
$('[data-toggle="tooltip"]').tooltip();

// Select/Deselect checkboxes
var checkbox = $('table tbody input[type="checkbox"]');
$("#selectAll").click(function () {
if (this.checked) {
checkbox.each(function () {
this.checked = true;
});
} else {
checkbox.each(function () {
this.checked = false;
});
}
});
checkbox.click(function () {
if (!this.checked) {
$("#selectAll").prop("checked", false);
}
});
});
		</script>
	</head>
	<body>
		<div class="container-xl">
			<div class="table-responsive">
				<div class="table-wrapper">
					{% block body %}
						<h1 style="text-align: center">Modification d'un patient</h1>

						{{ include('client/_form.html.twig', {'button_label': 'Enregistrer'}) }}
						<div class="row">
							<br>
							<div class="pull-left">
								<a href="{{ path('client_index') }}" class="btn btn-primary">
									<i class="material-icons">&#xe5c4;</i>
									<span>Liste des patients</span>
								</a>
							</div>
						</div>
						<div class="pull-right">
							<a href="{{ path('client_delete', {'id': client.id}) }}" class="btn btn-danger">
								<span>Supprimer ce patient</span>
							</a>
						</div>
					{% endblock %}
				</div>
			</div>
		</div>

	</body>
</html>

templates/client/index.html.twig
<!DOCTYPE html>

<title>Client index</title>

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>Bootstrap CRUD Data Table for Database with Modal Form</title>
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
		<style>
			body {
				color: #566787;
				background: #f5f5f5;
				font-family: 'Varela Round', sans-serif;
				font-size: 13px;
			}
			.table-responsive {
				margin: 30px 0;
			}
			.table-wrapper {
				background: #fff;
				padding: 20px 25px;
				border-radius: 3px;
				min-width: 1000px;
				box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
			}
			.table-title {
				padding: 16px 30px;
				color: #fff;
				min-width: 100%;
				margin: -20px -25px 10px;
			}
			.table-title h2 {
				margin: 5px 0 0;
				font-size: 24px;
			}
			.table-title .btn-group {
				float: right;
			}
			.table-title .btn {
				color: #fff;
				float: right;
				font-size: 13px;
				border: none;
				min-width: 50px;
				border-radius: 2px;
				border: none;
				outline: none !important;
				margin-left: 10px;
			}
			.table-title .btn i {
				float: left;
				font-size: 21px;
				margin-right: 5px;
			}
			.table-title .btn span {
				float: left;
				margin-top: 2px;
			}
			table.table tr th,
			table.table tr td {
				border-color: #e9e9e9;
				padding: 12px 15px;
				vertical-align: middle;
			}
			table.table tr th:first-child {
				width: 60px;
			}
			table.table tr th:last-child {
				width: 100px;
			}
			table.table-striped tbody tr:nth-of-type(odd) {
				background-color: #fcfcfc;
			}
			table.table-striped.table-hover tbody tr:hover {
				background: #f5f5f5;
			}
			table.table th i {
				font-size: 13px;
				margin: 0 5px;
				cursor: pointer;
			}
			table.table td:last-child i {
				opacity: 0.9;
				font-size: 22px;
				margin: 0 5px;
			}
			table.table td a {
				font-weight: bold;
				color: #566787;
				display: inline-block;
				text-decoration: none;
				outline: none !important;
			}
			table.table td a:hover {
				color: #2196F3;
			}
			table.table td a.edit {
				color: #FFC107;
			}
			table.table td a.delete {
				color: #F44336;
			}
			table.table td i {
				font-size: 19px;
			}
			table.table .avatar {
				border-radius: 50%;
				vertical-align: middle;
				margin-right: 10px;
			}
			.pagination {
				float: right;
				margin: 0 0 5px;
			}
			.pagination li a {
				border: none;
				font-size: 13px;
				min-width: 30px;
				min-height: 30px;
				color: #999;
				margin: 0 2px;
				line-height: 30px;
				border-radius: 2px !important;
				text-align: center;
				padding: 0 6px;
			}
			.pagination li a:hover {
				color: #666;
			}
			.pagination li.active a,
			.pagination li.active a.page-link {
				background: #03A9F4;
			}
			.pagination li.active a:hover {
				background: #0397d6;
			}
			.pagination li.disabled i {
				color: #ccc;
			}
			.pagination li i {
				font-size: 16px;
				padding-top: 6px
			}
			.hint-text {
				float: left;
				margin-top: 10px;
				font-size: 13px;
			}
			/* Custom checkbox */
			.custom-checkbox {
				position: relative;
			}
			.custom-checkbox input[type="checkbox"] {
				opacity: 0;
				position: absolute;
				margin: 5px 0 0 3px;
				z-index: 9;
			}
			.custom-checkbox label:before {
				width: 18px;
				height: 18px;
			}
			.custom-checkbox label:before {
				content: '';
				margin-right: 10px;
				display: inline-block;
				vertical-align: text-top;
				background: white;
				border: 1px solid #bbb;
				border-radius: 2px;
				box-sizing: border-box;
				z-index: 2;
			}
			.custom-checkbox input[type="checkbox"]:checked + label:after {
				content: '';
				position: absolute;
				left: 6px;
				top: 3px;
				width: 6px;
				height: 11px;
				border: solid #000;
				border-width: 0 3px 3px 0;
				transform: inherit;
				z-index: 3;
				transform: rotateZ(45deg);
			}
			.custom-checkbox input[type="checkbox"]:checked + label:before {
				border-color: #03A9F4;
				background: #03A9F4;
			}
			.custom-checkbox input[type="checkbox"]:checked + label:after {
				border-color: #fff;
			}
			.custom-checkbox input[type="checkbox"]:disabled + label:before {
				color: #b8b8b8;
				cursor: auto;
				box-shadow: none;
				background: #ddd;
			}
			/* Modal styles */
			.modal .modal-dialog {
				max-width: 400px;
			}
			.modal .modal-header,
			.modal .modal-body,
			.modal .modal-footer {
				padding: 20px 30px;
			}
			.modal .modal-content {
				border-radius: 3px;
				font-size: 14px;
			}
			.modal .modal-footer {
				background: #ecf0f1;
				border-radius: 0 0 3px 3px;
			}
			.modal .modal-title {
				display: inline-block;
			}
			.modal .form-control {
				border-radius: 2px;
				box-shadow: none;
				border-color: #dddddd;
			}
			.modal textarea.form-control {
				resize: vertical;
			}
			.modal .btn {
				border-radius: 2px;
				min-width: 100px;
			}
			.modal form label {
				font-weight: normal;
			}
		</style>
		<script>
			$(document).ready(function () { // Activate tooltip
$('[data-toggle="tooltip"]').tooltip();

// Select/Deselect checkboxes
var checkbox = $('table tbody input[type="checkbox"]');
$("#selectAll").click(function () {
if (this.checked) {
checkbox.each(function () {
this.checked = true;
});
} else {
checkbox.each(function () {
this.checked = false;
});
}
});
checkbox.click(function () {
if (!this.checked) {
$("#selectAll").prop("checked", false);
}
});
});
		</script>
	</head>
	<body>
		<div class="container-xl">
			<div class="table-responsive">
				<div class="table-wrapper">
					<div class="table-title">
						<div class="row">
							<div class="col-sm-12">
								<a href="{{ path('client_new') }}" class="btn btn-success">
									<i class="material-icons">&#xE147;</i>
									<span>Ajout d'un nouveau patient</span>
								</a>
							</div>
						</div>
					</div>
					{% block body %}
						<h1 style="text-align: center">Liste des patients</h1>

						<table class="table table-striped table-hover">
							<thead>
								<tr>
									<th>Identifiant</th>
									<th>Prénom</th>
									<th>Nom</th>
									<th>Date de naissance</th>
									<th>Actions</th>
								</tr>
							</thead>
							<tbody>
								{% for client in clients %}
									<tr>
										<td>{{ client.id }}</td>
										<td>{{ client.firstName }}</td>
										<td>{{ client.lastName }}</td>
										<td>{{ client.birthDate ? client.birthDate|date('Y-m-d') : '' }}</td>
										<td>
											<a href="{{ path('client_show', {'id': client.id}) }}">Afficher</a>
											<a href="{{ path('client_edit', {'id': client.id}) }}">Modifier</a>
										</td>
									</tr>
								{% else %}
									<tr>
										<td colspan="5">Aucun patient dans cette liste</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>

					{% endblock %}
				</div>
			</div>
		</div>
	</body>
</html></html>

templates/client/show.html.twig
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
		<style>
			body {
				color: #566787;
				background: #f5f5f5;
				font-family: 'Varela Round', sans-serif;
				font-size: 13px;
			}
			.table-responsive {
				margin: 30px 0;
			}
			.table-wrapper {
				background: #fff;
				padding: 20px 25px;
				border-radius: 3px;
				min-width: 1000px;
				box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
			}
			.table-title {
				padding: 16px 30px;
				color: #fff;
				min-width: 100%;
				margin: -20px -25px 10px;
			}
			.table-title h2 {
				margin: 5px 0 0;
				font-size: 24px;
			}
			.table-title .btn-group {
				float: right;
			}
			.table-title .btn {
				color: #fff;
				float: right;
				font-size: 13px;
				border: none;
				min-width: 50px;
				border-radius: 2px;
				border: none;
				outline: none !important;
				margin-left: 10px;
			}
			.table-title .btn i {
				float: left;
				font-size: 21px;
				margin-right: 5px;
			}
			.table-title .btn span {
				float: left;
				margin-top: 2px;
			}
			table.table tr th,
			table.table tr td {
				border-color: #e9e9e9;
				padding: 12px 15px;
				vertical-align: middle;
			}
			table.table-striped tbody tr:nth-of-type(odd) {
				background-color: #fcfcfc;
			}
			table.table-striped.table-hover tbody tr:hover {
				background: #f5f5f5;
			}
			table.table th i {
				font-size: 13px;
				margin: 0 5px;
				cursor: pointer;
			}
			table.table td:last-child i {
				opacity: 0.9;
				font-size: 22px;
				margin: 0 5px;
			}
			table.table td a {
				font-weight: bold;
				color: #566787;
				display: inline-block;
				text-decoration: none;
				outline: none !important;
			}
			table.table td a:hover {
				color: #2196F3;
			}
			table.table td a.edit {
				color: #FFC107;
			}
			table.table td a.delete {
				color: #F44336;
			}
			table.table td i {
				font-size: 19px;
			}
			table.table .avatar {
				border-radius: 50%;
				vertical-align: middle;
				margin-right: 10px;
			}
			.pagination {
				float: right;
				margin: 0 0 5px;
			}
			.pagination li a {
				border: none;
				font-size: 13px;
				min-width: 30px;
				min-height: 30px;
				color: #999;
				margin: 0 2px;
				line-height: 30px;
				border-radius: 2px !important;
				text-align: center;
				padding: 0 6px;
			}
			.pagination li a:hover {
				color: #666;
			}
			.pagination li.active a,
			.pagination li.active a.page-link {
				background: #03A9F4;
			}
			.pagination li.active a:hover {
				background: #0397d6;
			}
			.pagination li.disabled i {
				color: #ccc;
			}
			.pagination li i {
				font-size: 16px;
				padding-top: 6px
			}
			.hint-text {
				float: left;
				margin-top: 10px;
				font-size: 13px;
			}

			/* Modal styles */
			.modal .modal-dialog {
				max-width: 400px;
			}
			.modal .modal-header,
			.modal .modal-body,
			.modal .modal-footer {
				padding: 20px 30px;
			}
			.modal .modal-content {
				border-radius: 3px;
				font-size: 14px;
			}
			.modal .modal-footer {
				background: #ecf0f1;
				border-radius: 0 0 3px 3px;
			}
			.modal .modal-title {
				display: inline-block;
			}
			.modal .form-control {
				border-radius: 2px;
				box-shadow: none;
				border-color: #dddddd;
			}
			.modal textarea.form-control {
				resize: vertical;
			}
			.modal .btn {
				border-radius: 2px;
				min-width: 100px;
			}
			.modal form label {
				font-weight: normal;
			}
		</style>
		<script>
			$(document).ready(function () { // Activate tooltip
$('[data-toggle="tooltip"]').tooltip();

// Select/Deselect checkboxes
var checkbox = $('table tbody input[type="checkbox"]');
$("#selectAll").click(function () {
if (this.checked) {
checkbox.each(function () {
this.checked = true;
});
} else {
checkbox.each(function () {
this.checked = false;
});
}
});
checkbox.click(function () {
if (!this.checked) {
$("#selectAll").prop("checked", false);
}
});
});
		</script>
	</head>
	<body>
		<div class="container-xl">
			<div class="table-responsive">
				<div class="table-wrapper">

					{% block body %}
						<h1 style="text-align: center">Détails du patient</h1>

						<table class="table">
							<tbody>
								<tr>
									<th>Identifiant</th>
									<td>{{ client.id }}</td>
								</tr>
								<tr>
									<th>Prénom</th>
									<td>{{ client.firstName }}</td>
								</tr>
								<tr>
									<th>Nom</th>
									<td>{{ client.lastName }}</td>
								</tr>
								<tr>
									<th>Date de naissance</th>
									<td>{{ client.birthDate ? client.birthDate|date('Y-m-d') : '' }}</td>
								</tr>
							</tbody>
						</table>
						<div class="row">
							<div class="col-md-">
								<a href="{{ path('client_index') }}" class="btn btn-success">
									<i class="material-icons">&#xe5c4;</i>
									<span>Liste des patients</span>
								</a>

							</div>

							<div class="col-md-3"></div>
							<div class="col-md-3">
								<a href="{{ path('client_edit', {'id': client.id}) }}" class="btn btn-warning">
									<i class="material-icons">&#xe3c9;</i>
									<span>Modifier ce patient</span>
								</a>
							</div>
							<div class="col-md-3">
								<a href="{{ path('client_delete', {'id': client.id}) }}" class="btn btn-danger">
									<i class="material-icons">&#xe872;</i>
									<span>Supprimer ce patient</span>
								</a>
							</div>
						</div>
					{% endblock %}
				</div>
			</div>
		</div>
	</body>
</html></html>